### ISSUE TITLE
Error when populating listview dynamically (via Internet). Sectionizer tries to sectionize list rows when none of the list items are loaded yet.

### ISSUE THREAD

**Issue by TheAksh** [nolanlawson/SuperSaiyanScrollView#18]
Please help me out. TIA :)

If I sectionize ONLY after the entire listview is populated dynamically, then the library gives me an error : 

**Caused by: java.lang.NullPointerException: sectionizer cannot be null! Did you remember to call setSectionizer() or setMultipleSectionizer()?**

If I sectionize before the listview is populated dynamically with a random temporary value and resectionize after the listview is populated dynamically , then too I get the error : 

**Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                            at com.nolanlawson.supersaiyan.SectionedListAdapter.isEnabled(SectionedListAdapter.java:260)
                                                                            at com.felipecsl.quickreturn.library.widget.QuickReturnAdapter.isEnabled(QuickReturnAdapter.java:42)
                                                                            at android.widget.ListView.lookForSelectablePosition(ListView.java:2041)
                                                                            at android.widget.ListView.setAdapter(ListView.java:499)
                                                                            at akshapps.testinglistview.MainActivity.onCreate(MainActivity.java:126)**

**Comment by nolanlawson** [comment]
Sorry, I don't really remember this library very well, nor was I wise enough to write tests for it. :/ Maybe the issue is that you can only sectionize once? I'm pretty sure I don't allow you to dynamically resectionize. I.e. you can only call `setSectionizer()` once IIRC. Sorry I can't provide many more details than that.
